### ISSUE TITLE
Post: New spots

### ISSUE THREAD

**Issue by davatron5000** [Paravel/DayTrip-Blog#2]

**Comment by raygunray** [comment]
Y'all check this post for me - 

https://github.com/Paravel/DayTrip-Blog/blob/gh-pages/_drafts/newspots.markdown

Feel free to edit. I say we post this after Trent's spot sharing post.

**Comment by davatron5000** [comment]
Only typo I saw was "Betram", should be "Bertram"

**Comment by davatron5000** [comment]
FWIW, I don't think we should block news unless its absolutely necessary. Puts a lot of pressure on me to stop progress on what I'm working on to complete other new issues just to keep the blog pipeline running.

**Comment by raygunray** [comment]
I don't know what the status of Trent's post is. I was waiting to hear from him before I posted mine (I know he was trying to get it out yesterday).  If you'd rather post mine instead of waiting to hear from Trent - feel free. I did want him to proof mine as well, but that's probably NBD. 

Not sure where the pressure is coming from? I don't think anyone needs to stress about keeping the blog pipeline running. I also don't want to feel pressure to get things out quicker than I'm physically able for the sake of a blog post. We shouldn't worry about that.
